{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  {{ .Values.configMap.dataKey }}: {{ .Values.configMap.dataValue }}
{{- end}}