apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "baseApp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "baseApp.selectorLabels" . | nindent 4 }}